### ISSUE TITLE
Genestete Dokumente auslagern

### ISSUE THREAD

**Issue by rubengees** [KSWE-2016-17/TinyTaskDB#3]
Genestete Dokumente müssen in eigene Schematas gebracht werden, da die GraphQL Bibliothek Datenpopulation für diese nicht unterstützt.
Das würde konkret user.ratings und task.applications betreffen. Neue Schemata wären dann:

- `ratingSchema`
- `applicationSchema`

Sollten noch weitere Verlinkungen hinzugefügt werden, müsste das dort auch gemacht werden.

**Comment by Exormeter** [comment]
Neue Schemas erstellt und alte rausgezogen
