### ISSUE TITLE
Ids im Taskschema von Number zu String ändern

### ISSUE THREAD

**Issue by rubengees** [KSWE-2016-17/TinyTaskDB#4]
Da die Ids auch Buchstaben beinhalten können, gibt es ansonsten Probleme.
Zum anderen sorgt das für Konsistenz für mit den anderen Ids, welche Strings sind.

**Comment by Exormeter** [comment]
Done

**Comment by cemizm** [comment]
done. done.

**Comment by rubengees** [comment]
Works :ok_hand:

**Comment by kschima** [comment]
👍👍
